modified read-menu to use case instead of ifs

diff --git a/read-menu b/read-menu
--- a/read-menu
+++ b/read-menu
@@ -13,31 +13,23 @@ Select an option:
 "
 read -p "Enter selection [0-3] > "
 
-if grep ^[0-3]$ <<< "$REPLY"; then
-  if [ "$REPLY" -eq 0 ]; then
-    echo "Program terminated."
-    exit
-  fi
-  if [ "$REPLY" -eq 1 ]; then
-    echo "Hostname: $HOSTNAME"
-    uptime
-    exit
-  fi
-  if [ "$REPLY" -eq 2 ]; then
-    df -h
-    exit
-  fi
-  if [ "$REPLY" -eq 3 ]; then
-    if [ "$(id -u)" -eq 0 ]; then
-      echo "Home Space Utilization (All Users)"
-      du -sh /home/*
-    else
-      echo "Home Space Utilization ($USER)"
-      du -sh "$HOME"
-    fi
-    exit
-  fi
-else
-  echo "Invalid entry." >&2
-  exit 1
-fi
+case "$REPLY" in
+  0)  echo "Program terminated."
+      ;;
+  1)  echo "Hostname: $HOSTNAME"
+      uptime
+      ;;
+  2)  df -h
+      ;;
+  3)  if [ "$(id -u)" -eq 0 ]; then
+        echo "Home Space Utilization (All Users)"
+        du -sh /home/*
+      else
+        echo "Home Space Utilization ($USER)"
+        du -sh "$HOME"
+      fi
+      ;;
+  *)  echo "Invalid entry" >&2
+      exit 1
+      ;;
+esac
